import = ["/home/klaus/.config/bspwm/alacritty/colors.yml"]
#live_config_reload = true

[colors]
#draw_bold_text_with_bright_colors = true

[cursor]
#unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11.5

[font.bold]
family = "Hack"
style = "Bold"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_title = true
history = 10000
multiplier = 3
opacity = 0.5
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 10
y = 10
